version: "3.8"

services:
  envoy:
    depends_on:
     - product-service
    image: envoyproxy/envoy:v1.19.1
    container_name: envoy
    ports:
      - "10000:10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml"]

  product-service:
    depends_on:
      - mongo
    image: tuin/bb-product-service
    container_name: product-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ProductDatabase__ConnectionString=mongodb://root:pass@mongo:27017/
    ports:
      - "8080:80"
      - "8081:443"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
