version: "3.1"

services:
  product-service:
    image: tuin/bb-product-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ProductDatabase__ConnectionString=mongodb://root:pass@krakend-mongo-1:27017/
    ports:
      - "8080:80"
      - "8081:443"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/


  krakend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

